modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
#issueTrackerURL=""
[[mods]]
modId = "realisticnametag"
version = "0.2"
displayName = "Realistic Nametag"
#updateJSONURL=""
#displayURL=""
#logoFile=""
credits="Spitfox"
authors = "JustusWalterHelk, lu3arm"
displayTest="MATCH_VERSION"
description = '''Allows the player to re-use nametags. Right click a named entity with a shear.'''
[[dependencies.realisticnametag]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.realisticnametag]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"